# Generated by Django 4.2.2 on 2023-08-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_mane', models.CharField(max_length=128)),
                ('Lest_Name', models.CharField(max_length=128)),
                ('rank', models.IntegerField(choices=[(1, 'Admin'), (2, 'staff'), (3, 'CRM')])),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('time_date', models.DateTimeField(auto_now_add=True)),
                ('immage', models.ImageField(upload_to='content')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.author')),
            ],
        ),
    ]
